language: r

r_packages:
  - dplyr
  - lazyeval
  - scales
  - assertthat
  - knitr
  - testthat
  - rmarkdown

r_github_packages:
  - gforge/htmlTable@develop
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'
